// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARtCXYxt0Um4DkDDi4BoAyow0Z5ZqmhSU',
    appId: '1:460532146091:web:6448f38c99744320957cee',
    messagingSenderId: '460532146091',
    projectId: 'fise-app-319c9',
    authDomain: 'fise-app-319c9.firebaseapp.com',
    storageBucket: 'fise-app-319c9.appspot.com',
    measurementId: 'G-P04CHG12SX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFMX4e0erOkCrHMFhZZP2qRAN4mvnMPEQ',
    appId: '1:460532146091:android:e123bd8afbe3696a957cee',
    messagingSenderId: '460532146091',
    projectId: 'fise-app-319c9',
    storageBucket: 'fise-app-319c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQgtRntC9JlLLAmZfBjV1mfe9vvamR81o',
    appId: '1:460532146091:ios:1c35cc549ed629ff957cee',
    messagingSenderId: '460532146091',
    projectId: 'fise-app-319c9',
    storageBucket: 'fise-app-319c9.appspot.com',
    iosClientId: '460532146091-b1itivfrlr7bmcamcfkor56bv0brk8o5.apps.googleusercontent.com',
    iosBundleId: 'com.example.fiseApp',
  );
}
